#!/bin/bash
# Generate config file and execute server.

error=0

if [ "X${LDAP}" = Xenabled ] ; then
if [ "X${LDAPAUTH_URL}" = X ] ; then
   >&2 echo Error: LDAP is enabled, but LDAPAUTH_URL is not defined
   error=1
fi
if [ "X${LDAPAUTH_BINDDN}" = X ] ; then
   >&2 echo Warning: LDAP is enabled, but LDAPAUTH_BINDDN is not defined
fi
if [ "X${LDAPAUTH_BINDCREDENTIALS}" = X ] ; then
   >&2 echo Error: LDAP is enabled, but LDAPAUTH_BINDCREDENTIALS is not defined
   error=1
fi
if [ "X${LDAPAUTH_SEARCHBASE}" = X ] ; then
   >&2 echo Error: LDAP is enabled, but LDAPAUTH_SEARCHBASE is not defined
   error=1
fi
if [ "X${CLIENT_ID}" = X ] ; then
   >&2 echo Error: LDAP is enabled, but CLIENT_ID is not defined
   error=1
fi
fi

if [ "X${AUTH0DOMAIN}" != X -a "X${CLIENT_ID}" = X ] ; then
   >&2 echo Error: AUTH0DOMAIN is given, but CLIENT_ID is not defined
   error=1
fi

if [ "X${CLIENT_ID}" != X -a "X${CLIENT_SECRET}" = X ] ; then
   >&2 echo Error: CLIENT_ID is given, but CLIENT_SECRET is not defined
   error=1
fi

if [ $error -eq 1 ] ; then
   # Use exit code 0 to prevent container restart.
   exit 0
fi

##### END Error checking

# Redirect following echos to config file.
{

echo "{"

# Output LDAP config if defined.
if [ "X${LDAP}" = Xenabled ] ; then
>&2 echo LDAP is enabled
echo '  "ldap": {'
env | awk '
    BEGIN {
        q="\"";
        # Fix case of config options per https://github.com/vesse/node-ldapauth-fork
        e2j["binddn"] = "bindDn";
        e2j["bindcredentials"] = "bindCredentials";
        e2j["searchbase"] = "searchBase";
        e2j["searchfilter"] = "searchFilter";
        e2j["searchattributes"] = "searchAttributes";
        e2j["bindproperty"] = "bindProperty";
        e2j["searchscope"] = "searchScope";

        e2j["groupsearchbase"] = "groupSearchBase";
        e2j["groupsearchfilter"] = "groupSearchFilter";
        e2j["groupsearchattributes"] = "groupSearchAttributes";
        e2j["groupdnproperty"] = "groupDnProperty";
        e2j["groupsearchscope"] = "groupSearchScope";

        e2j["includeraw"] = "includeRaw";

        e2j["tlsoptions"] = "tlsOptions";
        e2j["socketpath"] = "socketPath";
        e2j["connecttimeout"] = "connectTimeout";
        e2j["idletimeout"] = "idleTimeout";
        e2j["strictdn"] = "strictDN";
        e2j["queuesize"] = "queueSize";
        e2j["queuetimeout"] = "queueTimeout";
        e2j["queuedisable"] = "queueDisable";

        # Override quote for numeric/logical options.
        quote["timeout"] = "";
        quote["connectTimeout"] = "";
        quote["idleTimeout"] = "";
        quote["reconnect"] = "";
        quote["includeRaw"] = "";
        quote["cache"] = "";
        quote["strictDN"] = "";
        quote["queueSize"] = "";
        quote["queueTimeout"] = "";
        quote["queueDisable"] = "";

        # Override quote for list/array options.
        # Example for setting searchAttributes: 
        # If the following is defined in the container .env file:
        #    LDAPAUTH_SEARCHATTRIBUTES=["uid","memberOf"]
        # then the value written to config.json will be
        #    "searchAttributes": ["uid", "memberOf"]
        quote["searchAttributes"] = "";

        # Set defaults.
        def["timeout"] = "5000";
        def["connectTimeout"] = "10000";
        def["reconnect"] = "true";
        def["searchFilter"] = "(CN={{username}})";
        def["searchAttributes"] = "[\"uid\", \"mail\", \"displayName\", \"memberOf\"]";

    }
    /^LDAPAUTH_/ {
        var=tolower($0); sub(/=.*/,"",var); sub(/ldapauth_/,"",var);
        if (e2j[var]) { var = e2j[var]; }
        val=$0; sub(/[^=]*=/,"",val);
        if (var in quote) { vq = quote[var]; } else { vq = q; }
        if (var in def) delete def[var];
        print "    " q var q ": " vq val vq ",";
    }
    END {
        for (var in def) {
            if (var in quote) { vq = quote[var]; } else { vq = q; }
            print "    " q var q ": " vq def[var] vq ",";
        }
    }'
echo '    "enabled": true'
if [ "X${CLIENT_ID}" = X ] ; then
    echo '  }'
else
    echo '  },'
fi
fi

# Output JWT config if defined.
if [ "X${CLIENT_ID}" != X ] ; then
>&2 echo JWT is enabled
sed -e "s/CLIENT_ID/${CLIENT_ID}/" \
    -e "s/CLIENT_SECRET/${CLIENT_SECRET}/" \
    -e "s/SECRET_BASE64/${SECRET_BASE64:-false}/" \
    -e "s/JWT_TIMEOUT_UNITS/${JWT_TIMEOUT_UNITS:-days}/" \
    -e "s/JWT_TIMEOUT/${JWT_TIMEOUT:-2}/" \
<< HERE
	"jwt": {
                "clientid": "CLIENT_ID",
		"secret": "CLIENT_SECRET",
                "base64": SECRET_BASE64,
                "timeout": JWT_TIMEOUT,
                "timeout_units": "JWT_TIMEOUT_UNITS"
	}
HERE
fi

# If env DEBUG defined, turn on debugging
if [ "X${DEBUG}" != X ] ; then
>&2 echo DEBUG is enabled
 echo ' ,
	"debug": "true"'
fi

# If env SSL defined, use SSL
if [ "X${SSL}" != X ] ; then
>&2 echo Using SSL
 echo ' ,
	"ssl": "true"'
fi

echo "}"


# End redirection.
} > config/config.json

# Execute server
exec npm start

# Should not happen.  Use exit code 0 to prevent container restart.
exit 0
