name: Test Suite

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build CI Docker image
      run: docker build --target ci -t ldap-jwt-ci .
    - name: Run tests
      run: |
        docker run --rm \
          -e BUILD_TARGET=ci \
          -e CLIENT_ID=myclientid \
          -e CLIENT_SECRET=myclientsecret \
          -e LDAP=enabled \
          -e LDAPAUTH_BINDDN_PREFIX="cn=" \
          -e LDAPAUTH_BINDDN_SUFFIX=",dc=example,dc=com" \
          -e LDAPAUTH_SEARCHBASE="dc=example,dc=com" \
          -e LDAPAUTH_URL=ldap://localhost:3004 \
          -e LOG_LEVEL=info \
          -e SSL=false \
          ldap-jwt-ci
